---
apiVersion: skaffold/v4beta2
kind: Config
manifests:
  kustomize:
    paths:
      - manifests/base
build:
  artifacts:
    - image: ghcr.io/carhartl/cluster-housekeeping
      context: .
deploy:
  kubectl:
    flags:
      apply: ["--namespace=housekeeping"]
      delete: ["--namespace=housekeeping"]
