---
apiVersion: batch/v1
kind: Job
metadata:
  name: label-ns
  labels:
{{- include "housekeeping.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      labels:
{{- include "housekeeping.labels" . | indent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: label-ns
      containers:
        - name: labeler
          image: bitnami/kubectl:latest
          command:
            - kubectl
            - label
            - ns
            - "{{ .Release.Namespace }}"
            - "pod-security.kubernetes.io/enforce=restricted"
            - "pod-security.kubernetes.io/enforce-version=latest"
            - "pod-security.kubernetes.io/warn=restricted"
            - "pod-security.kubernetes.io/warn-version=latest"
  ttlSecondsAfterFinished: 300
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-ns
  labels:
{{- include "housekeeping.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: label-ns
  labels:
{{- include "housekeeping.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: ["{{ .Release.Namespace }}"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Namespace }}:label-ns"
  labels:
{{- include "housekeeping.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
subjects:
  - kind: ServiceAccount
    name: label-ns
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: label-ns
  apiGroup: rbac.authorization.k8s.io
