{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "pod-reader") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Namespace }}:pod-reader"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ .Release.Namespace }}"
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: ""
{{- end}}