---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
subjects:
  - kind: ServiceAccount
    namespace: "{{ .Release.Namespace }}"
    name: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: ""
