{{- $rolename := printf "%s-pod-reader" .Release.Name -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ $rolename }}"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Namespace }}:{{ $rolename }}"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ .Release.Namespace }}"
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: "{{ $rolename }}"
  apiGroup: ""
{{- end}}